name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bdd/setup-go
        with:
          go-version: '>=1.5 <2'

      - name: Build
        run: ./scripts/build

      - name: Test
        run: go test ./...
