name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bdd/setup-go@main
        with:
          go-version: '>=1.16 <2'
          version-resolver: 'dist'

      - run: ./scripts/build

      - run: go test ./...
