name: depaware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: bdd/setup-go@main
      with:
        go-version: '>=1.5 <2'
        version-resolver: 'dist'

    - name: depaware runitor
      run: go run github.com/tailscale/depaware -goos "linux,darwin,freebsd,openbsd,windows" -check bdd.fi/x/runitor/cmd/runitor

    - name: depaware internal
      run: go run github.com/tailscale/depaware -goos "linux,darwin,freebsd,openbsd,windows" -check bdd.fi/x/runitor/internal
