name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      # "/repos/:owner/:repo/releases" is gated by "contents" permission.
      # https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-contents
      contents: write

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - run: go test -race ./...

      - run: ./scripts/build dist-all

      - uses: svenstaro/upload-release-action@c2b649c57ea652f7011a52950438ba6de235be33
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
          file_glob: true
          file: build/*
          overwrite: true
